#!/usr/bin/env python

import os
from sys import argv
from hi.driver import HFDriver

if __name__ != "__main__":
  raise RuntimeError('Must run this file as the main program!')

hfd = HFDriver(argv)
hfd.run()
